# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: az-pool


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Step 3: Run code linting (optional, for code quality checks)
- script: |
    npm run lint
  displayName: 'Run Linter'

# Step 4: Run tests (optional, based on your project setup)
- script: |
    npm test
  displayName: 'Run Unit Tests'

# Step 5: Copy necessary files to Artifact Staging Directory
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp -R ./* $(Build.ArtifactStagingDirectory)
  displayName: 'Copy files to Artifact Staging Directory'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

